### ISSUE TITLE
Use `inspect_container` instead of `containers` for polling.

### ISSUE THREAD

**Issue by ssanderson** [jupyter/dockerspawner#19]
`DockerSpawner.get_container` currently uses the `containers` api from docker-py to poll containers.  This has three issues:
1. It pulls far more information than it needs to.  We get info on *ALL* containers, iterate over them, find the one that matches the container we care about, then throw it away.
2. We have to parse the result to extract useful information, which can lead to bugs in corner cases (c.f. 4e23b6f3a8a7035f99a87870ec6bff23d2ce8481).
3. The information actually returned by `container` is fairly limited compared to the information actually available from the docker daemon.

 A far better alternative, IMO, would be to use `inspect_container` to request detailed information on the specific container we actually care about.

**Comment by ssanderson** [comment]
@minrk @rgbkrk I'm looking at switching over to using this for Quantopian's spawner subclass this morning.  Any reason not to do this upstream as well?

**Comment by minrk** [comment]
That seems better, I just didn't know there was another API. Don't ascribe too much intent to what we are doing, sometimes it's just the first thing we found that works.

With @jhamrick's deployment of a relatively large number of containers, I've been thinking about coming up with a way that each poll wouldn't need to make an API call against docker. If the DockerSpawner class used a global poll that queried all containers, there would only need to be one poll interval instead of one per Spawner, and then Spawner.poll would actually look at a cached value and return immediately. It would probably need to use direct polling for the shutdown sequence, but I think that's okay.

I think for the idle case, using an event model instead of polling is probably a better model for large numbers of containers.

**Comment by ssanderson** [comment]
PR for this is here: https://github.com/jupyter/dockerspawner/pull/20

**Comment by ssanderson** [comment]
@minrk I've thought for a while that we might be better served by having a single, global Spawner that's responsible for polling all users.

**Comment by minrk** [comment]
I think global polling makes sense, but I think I do prefer 1 object per server in general to a single object for managing all servers (that's the Hub), or adding a SpawnerManager layer in between the Application and each Spawner. The poller can still be global via `@classmethod`, so we don't need to change the object relationships to get more efficient polling.

**Comment by ssanderson** [comment]
My specific concern w/r/t the spawner-per-user configuration is that we store the spawners on sqlalchemy objects but don't actually persist them, which forces us to only use one session per hub or else the ORM objects flush their non-persisted state between session refreshes.  This is a bit of an anti-pattern as far as I can tell from my time working with SQLAlchemy.  It's less problematic in Jupyterhub than it might be otherwise because:
1. Jupyterhub's scaling ambitions are relatively modest.
2. Each Jupyterhub has only a single thread of execution with access to the database.

Even so though, having a shared global session has a bunch of unpleasant side-effects: most notably the fact that you have to assume a rollback and/or commit will occur on the session at every yield point.

**Comment by minrk** [comment]
Fair criticism, I think you have more experience with this sort of thing than I do. Would you create a new db connection and session for each request? Wouldn't we still have to force db commit or rollback on every yield to avoid races between multiple requests touching the same part of the database?

I still don't like the idea a global SpawnerManager. I'm trying to avoid the Manager patterns we use all over IPython because they sometimes feel like abstractions for abstraction's sake. In the subprocess case, I don't see anything for a global object to do, since there isn't any common state or common anything across spawners. l think docker is an exception to that, not the rule, and class-level globals should address the docker case well, similar to what tornado does with the StaticFileHandler vs other stateless handlers.

How would you propose the single global Spawner work differently from the independent Spawners, or would you add a Manager class on top of separate Spawners?

> My specific concern w/r/t the spawner-per-user configuration is that we store the spawners on sqlalchemy objects but don't actually persist them

Would it solve the problem if we had a higher level User object that **has a**n `orm.User` and the non-persisted attributes that I have stuck on `orm.User`, but probably shouldn't have? If that's the specific anti-pattern, I think we can work it out and restructure a few methods to avoid this particular relationship. I added non-persisted attributes to orm.User because I didn't see a problem with doing so, but if there is a problem, I'm happy to try a different pattern.

This stuff is still an experiment at this point, so I'm okay with major changes, if we want to try something new.

**Comment by ssanderson** [comment]
> Wouldn't we still have to force db commit or rollback on every yield to avoid races between multiple requests touching the same part of the database?

Only if you actually caree about the order in which updates got applied, which I don't think is the case for anything that happens in the Hub.  For example, it's perfectly fine to make modification to a User's `last_modified` in one session and a modification to their server IP in another session, because SQLAlchemy is smart enough to only submit updates for the attributes that you actually touched in your session.

> I still don't like the idea a global SpawnerManager. I'm trying to avoid the Manager patterns we use all over IPython because they sometimes feel like abstractions for abstraction's sake. In the subprocess case, I don't see anything for a global object to do, since there isn't any common state or common anything across spawners. 

The main benefit I see to the global SpawnManager (or just a single global `Spawner`), is that it makes broadcasting operations possible.  If you have a fleet of Spawner objects, each of which is logically responsible for a single Notebook Server, then there's no clean way to say "talk to all the notebook servers at once" without arbitrarily making one of the Spawners special.  The obvious case for an operation where broadcasting is desirable is polling all the containers in one go, but in general any time you want to do some action to all your Notebook Servers, if it's possible to perform that action more efficiently by talking to all the servers in one go, then you're going to want some object that's logically responsible for all the Notebook servers, not just a single server.  Another example where this would be reasonable would be implementing a `stop_all` by sending a SIGTERM to a process group rather than sending TERMs to individual processes.

It's also worth noting that there's nothing preventing the implementation of a global manager from delegating to sub-objects that are responsible for individual servers: it's easy to implement `poll_all` or `shutdown_all` as a for-loop over a list of Spawners; it's hard to implement `poll_all` as a broadcasting operation without having some object that's morally responsible for **all** the servers rather than a single server.

You could argue that the object responsible for doing broadcast operations should be the Hub itself, but I'd argue that:

1. The Hub has enough responsibilities (managing graceful startup and shutdown, handling configuration, keeping track of the Proxy, setting up tornado handlers, etc.) that it makes sense to delegate the task of talking to all the notebook servers to a dedicated subsystem.
2. It's often going to be the case that the manner in which you want to implement some broadcasting operation depends on the specific process backend.  Polling in a broadcasting manner is easy with servers spawned with Docker, but maybe not with POpen, whereas stopping might be easy to broadcast to standard processes but not to Docker containers.

> Would it solve the problem if we had a higher level User object that has an orm.User and the non-persisted attributes that I have stuck on orm.User, but probably shouldn't have? If that's the specific anti-pattern, I think we can work it out and restructure a few methods to avoid this particular relationship.

This makes sense to me on the face of it.  One immediate question I'd have, given your distaste for spurious Manager classes (which in general I agree with by the way), is where you'd put all the non-ORM User objects?  If you ever want to do `for user in all_users`, then you need to stash them all somewhere accessible.  Right now we're effectively using the single global SQLAlchemy session as that stash, but if the point of this change would be to move non-persisted state out of SQLAlchemy, then it you'd have to have some sort of `TotallyNotAUserManager` object keeping track of them all.

**Comment by ssanderson** [comment]
@minrk sorry for the wall of text here; hopefully it came out semi-coherent.

**Comment by minrk** [comment]
@ssanderson not a problem, I appreciate your help figuring this out.

> Only if you actually care about the order in which updates got applied, which I don't think is the case for anything that happens in the Hub.

It seems like the commit is still required, otherwise how do we deal with one request yielding to another request for the same action (e.g. two starts of the same server)? I'm not super concerned about that case, but it seems difficult to recover from that if db operations are allowed to be pending but not committed at yield time.

I think it's worth giving the single Spawner idea more consideration. Since almost all operations (including polling) operate on one container at a time, I'm not quite sure how to rewrite things such that it would make things simpler, but that's mostly because I've already written everything with the current model.

> where you'd put all the non-ORM User objects?

Off the top of my head, for the higher level user container, I think a dict keyed by the unique id in the users table would be enough. For iteration, I would probably still iterate with `db.query(orm.User)`, and then get the higher level object with a `user_from_orm_user` wrapper that gets the associated User from the global dict, populating it if the db entry hasn't been seen before.

If there's a need for class that's more than a dict of users, that's fine, but I'm not sure that would be needed.
