### ISSUE TITLE
make it easier to switch base image

### ISSUE THREAD

**Issue by minrk** [jupyter/dockerspawner#82]
@carolynvs wrote [a great post](http://carolynvanslyck.com/blog/2016/03/use-jupyter-stacks-with-docker/) about mixing jupyter-stacks with JupyterHub.

in the section about the Dockerfile, the source from the single-user dockerfile is copied, which makes perfect sense given how docker works, but it gave me an idea. Since the single-user stuff shouldn't be sensitive to the base image as long as jupyter is installed somewhere, maybe we should provide an official `rebase-image` command to do this, so it's easy for people to build their single-user images without maintaining copies of code that could get stale.

Rather than doing a one-time copy of the single-user image, you do `rebase-singleuser jupyter/<stack>` that does:

1. copy singleuser -> my-singleuser
2. modify FROM
3. `docker build -t singleuser my-singleuser`

Hopefully removing the need to copy implementation details of the single-user image.

The only fiddly bit I can see is the user and permission stuff, which broke when I switched it to our docker stacks because of the `jovyan` user.

cc @rgbkrk

**Comment by rgbkrk** [comment]
This is better than any approach I can currently think of (besides always bundling singleuser with a jupyter notebook install), though I still feel it is a bit murky to handle it like this.

**Comment by carolynvs** [comment]
A command could be useful, though I think the entire process could be performed with a single line of `curl | sed` + `docker build`.

Would it be crazy to push jupyter-stack images built for JupyterHub to DockerHub? e.g. jupyter/minimal-notebook would have a companion, jupyter/minimal-notebook-hub or something like that.

**Comment by rgbkrk** [comment]
> Would it be crazy to push jupyter-stack images built for JupyterHub to DockerHub?

/cc @parente for that one. Peter will have a better idea of the current maintenance burden.

**Comment by parente** [comment]
> which broke when I switched it to our docker stacks because of the jovyan user.

I'm not privy to the problem but, FWIW, the `NB_UID` env var can be set at runtime to change the UID of `jovyan` in every docker-stacks image (see https://github.com/jupyter/docker-stacks/blob/master/minimal-notebook/README.md#docker-options for example)

> Would it be crazy to push jupyter-stack images built for JupyterHub to DockerHub?

Not too crazy. I think. We can give it a shot with a few of the images to start and see how it goes.

- Pro: The new images would start `FROM` the existing ones and be quick to build.
- Con: They would rebuild every time the base images rebuilt. (But should still build quickly.)
- Pro: @jakirkham has gotten the stacks building on Travis so that we at least get a sniff test on new PRs and don't need to build/test everything manually. Adding new images isn't as burdensome as before.
- Con: Travis busts docker cache on every build after pulling the latest images from Docker Hub for unknown reasons, and so often times out.  So we still don't push from travis because of the above and still need to trigger (and retry) builds manually from a build VM.
- Pro: If the Docker Hub stats are to be believed, some of the images are far more popular than the others (https://gist.github.com/parente/316d5c242aeb484484c8). @jakirkham and I started chatting about removing the less popular ones (which are subsets of the others anyway) in order to speed up the build and reduce maintenance cost.

**Comment by minrk** [comment]
@parente I didn't mean to imply that it was a problem. It's just that the base image had a different user than the previous base image, so I had to change a line or two. That's the only thing that should not be 100% generic in the singleuser Dockerfile.

@carolynvs pushing single-user derivatives to docker-stacks makes sense to me. And since it really is as simple as curl + sed, as you say, building a singleuser stack from each notebook stack should be easy to automate.

**Comment by minrk** [comment]
#83 adds a script for quickly building a single-user image with a different base
